/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    packages: Package;
    devices: Device;
    'blog-posts': BlogPost;
    testimonials: Testimonial;
    faqs: Faq;
    'contact-submissions': ContactSubmission;
    'appointment-types': AppointmentType;
    'schedule-exceptions': ScheduleException;
    appointments: Appointment;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    packages: PackagesSelect<false> | PackagesSelect<true>;
    devices: DevicesSelect<false> | DevicesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'appointment-types': AppointmentTypesSelect<false> | AppointmentTypesSelect<true>;
    'schedule-exceptions': ScheduleExceptionsSelect<false> | ScheduleExceptionsSelect<true>;
    appointments: AppointmentsSelect<false> | AppointmentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    availability: Availability;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    availability: AvailabilitySelect<false> | AvailabilitySelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * URL parcasi. Bos birakilirsa baslitan otomatik uretilir.
   */
  slug: string;
  /**
   * Grid kartında görünen kısa açıklama.
   */
  summary: string;
  /**
   * lucide ikon adı (ör. heart-pulse, salad, baby).
   */
  icon?: string | null;
  category?:
    | (
        | 'kilo-yonetimi'
        | 'insulin-direnci-diyabet'
        | 'pcos'
        | 'hasimoto'
        | 'gebelik-emzirme'
        | 'glp1'
        | 'bolgesel'
        | 'surdurulebilir'
        | 'danismanlik'
        | 'diger'
      )
    | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  order?: number | null;
  seo?: {
    /**
     * Bos birakilirsa sayfa/kayit basligi kullanilir.
     */
    title?: string | null;
    /**
     * Arama sonucu/OG aciklamasi (~155 karakter).
     */
    description?: string | null;
    /**
     * OG paylasim gorseli (1200x630 onerilir).
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages".
 */
export interface Package {
  id: number;
  name: string;
  /**
   * URL parcasi. Bos birakilirsa baslitan otomatik uretilir.
   */
  slug: string;
  summary: string;
  sessions?: number | null;
  durationWeeks?: number | null;
  price: number;
  /**
   * İndirim varsa üstü çizili gösterilir.
   */
  oldPrice?: number | null;
  discountNote?: string | null;
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  familyDiscount?: boolean | null;
  /**
   * Ör. "İlk geldiğiniz görüşmede ücret alınmaktadır."
   */
  note?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "devices".
 */
export interface Device {
  id: number;
  name: string;
  /**
   * URL parcasi. Bos birakilirsa baslitan otomatik uretilir.
   */
  slug: string;
  tagline?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  benefits?:
    | {
        benefit: string;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  /**
   * URL parcasi. Bos birakilirsa baslitan otomatik uretilir.
   */
  slug: string;
  excerpt?: string | null;
  cover?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category?: ('beslenme' | 'kilo-yonetimi' | 'hastaliklar' | 'gebelik-cocuk' | 'tarifler' | 'yasam') | null;
  publishedAt?: string | null;
  seo?: {
    /**
     * Bos birakilirsa sayfa/kayit basligi kullanilir.
     */
    title?: string | null;
    /**
     * Arama sonucu/OG aciklamasi (~155 karakter).
     */
    description?: string | null;
    /**
     * OG paylasim gorseli (1200x630 onerilir).
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  /**
   * Gizlilik için tam isim yerine gösterilebilir (ör. A.Y.).
   */
  initials?: string | null;
  rating: number;
  text: string;
  source?: ('Google' | 'Doktorsitesi' | 'Direct') | null;
  service?: string | null;
  date?: string | null;
  /**
   * KVKK: yalnızca rıza alınan yorumlar yayınlanır.
   */
  consent: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category?: ('genel' | 'randevu' | 'paketler' | 'online' | 'cihazlar') | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  phone?: string | null;
  email?: string | null;
  subject?: string | null;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointment-types".
 */
export interface AppointmentType {
  id: number;
  name: string;
  /**
   * URL parcasi. Bos birakilirsa baslitan otomatik uretilir.
   */
  slug: string;
  durationMin: number;
  channel: 'online' | 'in_person' | 'both';
  description?: string | null;
  active?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule-exceptions".
 */
export interface ScheduleException {
  id: number;
  /**
   * Örn. 2026-07-15
   */
  date: string;
  type: 'closed' | 'custom';
  /**
   * Örn. 10:00
   */
  start?: string | null;
  /**
   * Örn. 14:00
   */
  end?: string | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments".
 */
export interface Appointment {
  id: number;
  slotKey?: string | null;
  date: string;
  startTime: string;
  durationMin: number;
  status: 'pending' | 'confirmed' | 'cancelled' | 'rescheduled' | 'completed' | 'no_show';
  appointmentType: number | AppointmentType;
  channel: 'online' | 'in_person';
  service?: (number | null) | Service;
  clientName: string;
  phone: string;
  email?: string | null;
  notes?: string | null;
  kvkkConsent: boolean;
  /**
   * Faz 3 (otomatik).
   */
  reminderSent?: boolean | null;
  paymentStatus?: ('none' | 'pending' | 'paid' | 'refunded') | null;
  /**
   * Faz 6.
   */
  paymentProvider?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'packages';
        value: number | Package;
      } | null)
    | ({
        relationTo: 'devices';
        value: number | Device;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'appointment-types';
        value: number | AppointmentType;
      } | null)
    | ({
        relationTo: 'schedule-exceptions';
        value: number | ScheduleException;
      } | null)
    | ({
        relationTo: 'appointments';
        value: number | Appointment;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  icon?: T;
  category?: T;
  body?: T;
  order?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages_select".
 */
export interface PackagesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  summary?: T;
  sessions?: T;
  durationWeeks?: T;
  price?: T;
  oldPrice?: T;
  discountNote?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  familyDiscount?: T;
  note?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "devices_select".
 */
export interface DevicesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tagline?: T;
  description?: T;
  benefits?:
    | T
    | {
        benefit?: T;
        id?: T;
      };
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  cover?: T;
  body?: T;
  category?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  initials?: T;
  rating?: T;
  text?: T;
  source?: T;
  service?: T;
  date?: T;
  consent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  subject?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointment-types_select".
 */
export interface AppointmentTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  durationMin?: T;
  channel?: T;
  description?: T;
  active?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule-exceptions_select".
 */
export interface ScheduleExceptionsSelect<T extends boolean = true> {
  date?: T;
  type?: T;
  start?: T;
  end?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments_select".
 */
export interface AppointmentsSelect<T extends boolean = true> {
  slotKey?: T;
  date?: T;
  startTime?: T;
  durationMin?: T;
  status?: T;
  appointmentType?: T;
  channel?: T;
  service?: T;
  clientName?: T;
  phone?: T;
  email?: T;
  notes?: T;
  kvkkConsent?: T;
  reminderSent?: T;
  paymentStatus?: T;
  paymentProvider?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  phone?: string | null;
  whatsapp?: string | null;
  email?: string | null;
  instagram?: string | null;
  instagramUrl?: string | null;
  address?: string | null;
  mapEmbedUrl?: string | null;
  workingHours?: string | null;
  hero?: {
    heading?: string | null;
    subheading?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
    portrait?: (number | null) | Media;
  };
  /**
   * Hero güven şeridi (ör. "18 yıl" / "deneyim").
   */
  trustStats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  reviewBadges?:
    | {
        source?: ('Google' | 'Doktorsitesi') | null;
        rating?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "availability".
 */
export interface Availability {
  id: number;
  /**
   * Her gün için açık/kapalı ve saat aralığı.
   */
  weekly?:
    | {
        day: 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun';
        enabled?: boolean | null;
        start?: string | null;
        end?: string | null;
        id?: string | null;
      }[]
    | null;
  slotIntervalMin?: number | null;
  bufferMin?: number | null;
  minLeadHours?: number | null;
  maxAdvanceDays?: number | null;
  lateToleranceMin?: number | null;
  rescheduleStandardDays?: number | null;
  rescheduleQuarterlyDays?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  phone?: T;
  whatsapp?: T;
  email?: T;
  instagram?: T;
  instagramUrl?: T;
  address?: T;
  mapEmbedUrl?: T;
  workingHours?: T;
  hero?:
    | T
    | {
        heading?: T;
        subheading?: T;
        ctaLabel?: T;
        ctaHref?: T;
        portrait?: T;
      };
  trustStats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  reviewBadges?:
    | T
    | {
        source?: T;
        rating?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "availability_select".
 */
export interface AvailabilitySelect<T extends boolean = true> {
  weekly?:
    | T
    | {
        day?: T;
        enabled?: T;
        start?: T;
        end?: T;
        id?: T;
      };
  slotIntervalMin?: T;
  bufferMin?: T;
  minLeadHours?: T;
  maxAdvanceDays?: T;
  lateToleranceMin?: T;
  rescheduleStandardDays?: T;
  rescheduleQuarterlyDays?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}